### PR TITLE
flutter non null safety and download manager changes (not working)

### PR DESCRIPTION
**Pull request by dabbler0349**

### CODE REVIEW

**Comment by dabbler0349** [comment]
pull request for wrong repo, my bad

**Comment by ethael** [comment]
Sad to see, that you forked our repo and with first commit deleted our license file. In most countries, this is called a theft.

**Comment by dabbler0349** [comment]
I'm still pretty new to open source evelopment and git and everything. I'll be sure to keep that in mind.

**Comment by dabbler0349** [comment]
sorry again

**Comment by ethael** [comment]
Well, hope you do. Good luck with your project.

**Pull request closed without merging**
